[2024-07-14T00:15:39.975+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T00:15:40.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: from_csv_to_pgsql.save_file_md_ledger_account_s.csv scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-14T00:15:40.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: from_csv_to_pgsql.save_file_md_ledger_account_s.csv scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-14T00:15:40.119+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T00:15:45.579+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_file_md_ledger_account_s.csv> on 2024-07-08 00:00:00+00:00
[2024-07-14T00:15:45.587+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=940) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T00:15:45.589+0000] {standard_task_runner.py:63} INFO - Started process 1140 to run task
[2024-07-14T00:15:45.587+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'from_csv_to_pgsql', 'save_file_md_ledger_account_s.csv', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/from_csv_to_pgsql.py', '--cfg-path', '/tmp/tmpitask54q']
[2024-07-14T00:15:45.591+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask save_file_md_ledger_account_s.csv
[2024-07-14T00:15:45.687+0000] {task_command.py:426} INFO - Running <TaskInstance: from_csv_to_pgsql.save_file_md_ledger_account_s.csv scheduled__2024-07-08T00:00:00+00:00 [running]> on host f4c752a3ffdd
[2024-07-14T00:15:46.022+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='from_csv_to_pgsql' AIRFLOW_CTX_TASK_ID='save_file_md_ledger_account_s.csv' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-14T00:15:46.026+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T00:15:46.365+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T00:15:46.367+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_pgsql.py", line 13, in load_csv_to_spark
    spark = spark_session()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_pgsql.py", line 9, in spark_session
    spark = SparkSession.builder.appName("AirflowETL").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-07-14T00:15:46.413+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=from_csv_to_pgsql, task_id=save_file_md_ledger_account_s.csv, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240714T001540, end_date=20240714T001546
[2024-07-14T00:15:46.503+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task save_file_md_ledger_account_s.csv ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 1140)
[2024-07-14T00:15:46.547+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T00:15:46.615+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T00:15:46.637+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
