[2024-07-19T19:55:51.704+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T19:55:51.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.extract_and_load_process manual__2024-07-19T19:50:33.310894+00:00 [queued]>
[2024-07-19T19:55:51.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.extract_and_load_process manual__2024-07-19T19:50:33.310894+00:00 [queued]>
[2024-07-19T19:55:51.779+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-19T19:55:51.798+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-19 19:50:33.310894+00:00
[2024-07-19T19:55:51.806+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_f_101_round_f', 'extract_and_load_process', 'manual__2024-07-19T19:50:33.310894+00:00', '--job-id', '633', '--raw', '--subdir', 'DAGS_FOLDER/сreate_and_fill_f101_round_f.py', '--cfg-path', '/tmp/tmp0x5_0jap']
[2024-07-19T19:55:51.808+0000] {standard_task_runner.py:91} INFO - Job 633: Subtask extract_and_load_process
[2024-07-19T19:55:51.818+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19008) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-19T19:55:51.818+0000] {standard_task_runner.py:63} INFO - Started process 19016 to run task
[2024-07-19T19:55:51.854+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_f_101_round_f.extract_and_load_process manual__2024-07-19T19:50:33.310894+00:00 [running]> on host 7c7e02e57379
[2024-07-19T19:55:51.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_f_101_round_f' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T19:50:33.310894+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T19:50:33.310894+00:00'
[2024-07-19T19:55:51.986+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T19:55:55.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T19:55:55.018+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/сreate_and_fill_f101_round_f.py", line 134, in extract_and_load_task
    schema = schemas[file_name]
             ~~~~~~~^^^^^^^^^^^
KeyError: 'dm_f101_round_f'
[2024-07-19T19:55:55.032+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_fill_f_101_round_f, task_id=extract_and_load_process, run_id=manual__2024-07-19T19:50:33.310894+00:00, execution_date=20240719T195033, start_date=20240719T195551, end_date=20240719T195555
[2024-07-19T19:55:55.047+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 633 for task extract_and_load_process ('dm_f101_round_f'; 19016)
[2024-07-19T19:55:55.056+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-19T19:55:55.073+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-19T19:55:55.091+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T19:55:55.100+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
