[2024-07-19T19:11:22.193+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T19:11:22.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.end_process manual__2024-07-19T19:10:42.958350+00:00 [queued]>
[2024-07-19T19:11:22.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.end_process manual__2024-07-19T19:10:42.958350+00:00 [queued]>
[2024-07-19T19:11:22.228+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-19T19:11:22.239+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): end_process> on 2024-07-19 19:10:42.958350+00:00
[2024-07-19T19:11:22.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_f_101_round_f', 'end_process', 'manual__2024-07-19T19:10:42.958350+00:00', '--job-id', '606', '--raw', '--subdir', 'DAGS_FOLDER/—Åreate_and_fill_f101_round_f.py', '--cfg-path', '/tmp/tmpm88m1m5_']
[2024-07-19T19:11:22.248+0000] {standard_task_runner.py:91} INFO - Job 606: Subtask end_process
[2024-07-19T19:11:22.270+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=15663) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-19T19:11:22.271+0000] {standard_task_runner.py:63} INFO - Started process 15664 to run task
[2024-07-19T19:11:22.290+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_f_101_round_f.end_process manual__2024-07-19T19:10:42.958350+00:00 [running]> on host 7c7e02e57379
[2024-07-19T19:11:22.362+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_f_101_round_f' AIRFLOW_CTX_TASK_ID='end_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T19:10:42.958350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T19:10:42.958350+00:00'
[2024-07-19T19:11:22.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T19:11:22.381+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-19T19:11:22.399+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T19:11:22.400+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T19:11:22.407+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=run_fill_f_101_round_f, task_id=end_process, run_id=manual__2024-07-19T19:10:42.958350+00:00, execution_date=20240719T191042, start_date=20240719T191122, end_date=20240719T191122
[2024-07-19T19:11:22.445+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-19T19:11:22.465+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T19:11:22.468+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
