[2024-07-19T19:21:36.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T19:21:36.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.fill_f101 manual__2024-07-19T19:21:12.430053+00:00 [queued]>
[2024-07-19T19:21:36.497+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.fill_f101 manual__2024-07-19T19:21:12.430053+00:00 [queued]>
[2024-07-19T19:21:36.499+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-19T19:21:36.511+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fill_f101> on 2024-07-19 19:21:12.430053+00:00
[2024-07-19T19:21:36.519+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_f_101_round_f', 'fill_f101', 'manual__2024-07-19T19:21:12.430053+00:00', '--job-id', '620', '--raw', '--subdir', 'DAGS_FOLDER/—Åreate_and_fill_f101_round_f.py', '--cfg-path', '/tmp/tmp16ajiasx']
[2024-07-19T19:21:36.521+0000] {standard_task_runner.py:91} INFO - Job 620: Subtask fill_f101
[2024-07-19T19:21:36.545+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16774) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-19T19:21:36.546+0000] {standard_task_runner.py:63} INFO - Started process 16775 to run task
[2024-07-19T19:21:36.562+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_f_101_round_f.fill_f101 manual__2024-07-19T19:21:12.430053+00:00 [running]> on host 7c7e02e57379
[2024-07-19T19:21:36.638+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_f_101_round_f' AIRFLOW_CTX_TASK_ID='fill_f101' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T19:21:12.430053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T19:21:12.430053+00:00'
[2024-07-19T19:21:36.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T19:21:36.657+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-19T19:21:36.668+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-19T19:21:36.679+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-19T19:21:36.693+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T19:21:36.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T19:21:36.704+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=run_fill_f_101_round_f, task_id=fill_f101, run_id=manual__2024-07-19T19:21:12.430053+00:00, execution_date=20240719T192112, start_date=20240719T192136, end_date=20240719T192136
[2024-07-19T19:21:36.721+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-19T19:21:36.742+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-19T19:21:36.745+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
