[2024-07-19T20:00:26.473+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T20:00:26.502+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.extract_and_load_process manual__2024-07-19T20:00:18.575359+00:00 [queued]>
[2024-07-19T20:00:26.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_f_101_round_f.extract_and_load_process manual__2024-07-19T20:00:18.575359+00:00 [queued]>
[2024-07-19T20:00:26.511+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-19T20:00:26.525+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-19 20:00:18.575359+00:00
[2024-07-19T20:00:26.532+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_f_101_round_f', 'extract_and_load_process', 'manual__2024-07-19T20:00:18.575359+00:00', '--job-id', '641', '--raw', '--subdir', 'DAGS_FOLDER/сreate_and_fill_f101_round_f.py', '--cfg-path', '/tmp/tmpu7sdvkpl']
[2024-07-19T20:00:26.534+0000] {standard_task_runner.py:91} INFO - Job 641: Subtask extract_and_load_process
[2024-07-19T20:00:26.559+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=20503) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-19T20:00:26.560+0000] {standard_task_runner.py:63} INFO - Started process 20504 to run task
[2024-07-19T20:00:26.575+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_f_101_round_f.extract_and_load_process manual__2024-07-19T20:00:18.575359+00:00 [running]> on host 7c7e02e57379
[2024-07-19T20:00:26.653+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_f_101_round_f' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T20:00:18.575359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T20:00:18.575359+00:00'
[2024-07-19T20:00:26.656+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T20:00:29.887+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T20:00:29.889+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/сreate_and_fill_f101_round_f.py", line 134, in extract_and_load_task
    schema = schemas[file_name]
             ~~~~~~~^^^^^^^^^^^
KeyError: 'dm_f101_round_f'
[2024-07-19T20:00:29.911+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=run_fill_f_101_round_f, task_id=extract_and_load_process, run_id=manual__2024-07-19T20:00:18.575359+00:00, execution_date=20240719T200018, start_date=20240719T200026, end_date=20240719T200029
[2024-07-19T20:00:29.943+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 641 for task extract_and_load_process ('dm_f101_round_f'; 20504)
[2024-07-19T20:00:29.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-19T20:00:30.015+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-19T20:00:30.035+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T20:00:30.042+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
